### PR TITLE
Add back random suggestions, Fix some bugs in searching

### PR DESCRIPTION
**Pull request by Nv7-GitHub**
This may not be up to your quality standards but it is fully functional and if I don't do this, most likely no one will. I want this in the game and this is fully functional. 

Also, you left the searching bug in the game, so I fixed it.

### CODE REVIEW

**Review by Filip9696 — APPROVED** [review]
This is good, we can accept this... only the last commit that is

**Comment by davecaruso** [comment]
one change per pr. i will review random suggestions later

**Comment by davecaruso** [comment]
not up to quality standards

**Comment by Nv7-GitHub** [comment]
What was wrong with the quality

**Pull request closed without merging**
