### PR TITLE
Searching & Random Lonely Suggestion/Up and Coming Suggestion

### PR DESCRIPTION
**Pull request by Nv7-GitHub**
This adds searching functionality to the game. This is currently only supported by the Nv7 Server.
Press any key to bring up the search menu.

### CODE REVIEW

**Comment by davecaruso** [comment]
havent tried it in game, but code seems fine. also has animations supposedly, very cool.

one issue i have with this is it puts the actual search functionality into each api itself, when it doesn't really need to be.

alternatively, you could just look at the currently owned elements onscreen, and change css display-- unless im missing some functionality in the search that the api could provide.

**Comment by Nv7-GitHub** [comment]
What I was wondering was what if you have a more efficient way of storage? Right now the searching algorithm is up to the api, so performance is not dependent on game code. If you had a more efficient method of searching (does indexeddb support searching?), you could make it more perform ant. However, if it is part of the game code, it can’t be changed.

**Comment by davecaruso** [comment]
you should just go off of the existing dom nodes already present on the page, wouldn't that be the fastest?

**Comment by Nv7-GitHub** [comment]
Now there is Radom Lonely suggestion and Up & coming suggestion

**Comment by Nv7-GitHub** [comment]
I fixed a lot of bugs

**Comment by davecaruso** [comment]
looks alright. ill check out features in game and roll out a new release for these

**Pull request merged**
